In [1]:
import torch

In [2]:
 sample = torch.randint(0,10,size=(3,))

In [3]:
expand = torch.randint(0,10,size=(3,2,2))

In [4]:
print(sample)
sample.size()

tensor([9, 9, 1])


torch.Size([3])

In [5]:
print(expand)
expand.size()

tensor([[[7, 1],
         [4, 8]],

        [[9, 2],
         [2, 5]],

        [[0, 7],
         [5, 1]]])


torch.Size([3, 2, 2])

In [6]:
sample_ = sample.unsqueeze(0).unsqueeze(0).unsqueeze(0)

In [7]:
match = (expand.unsqueeze(-1)== sample_).long()

In [8]:
match = torch.where(match>0)

In [9]:
match

(tensor([0, 1, 1, 2]),
 tensor([0, 0, 0, 1]),
 tensor([1, 0, 0, 1]),
 tensor([2, 0, 1, 2]))

In [10]:
sample[match[-1]]

tensor([1, 9, 9, 1])

In [11]:
expand[match[0]]

tensor([[[7, 1],
         [4, 8]],

        [[9, 2],
         [2, 5]],

        [[9, 2],
         [2, 5]],

        [[0, 7],
         [5, 1]]])

In [12]:
expand[match[0],match[1],match[2]]

tensor([1, 9, 9, 1])