In [71]:
import torch

In [72]:
 sample = torch.randint(0,10,size=(3,))

In [73]:
expand = torch.randint(0,10,size=(3,2,2))

In [74]:
print(sample)
sample.size()

tensor([6, 3, 7])


torch.Size([3])

In [75]:
print(expand)
expand.size()

tensor([[[7, 0],
         [3, 3]],

        [[1, 3],
         [6, 7]],

        [[9, 7],
         [8, 5]]])


torch.Size([3, 2, 2])

In [76]:
sample_ = sample.unsqueeze(0).unsqueeze(0).unsqueeze(0)

In [77]:
match = (expand.unsqueeze(-1)== sample_).long()

In [78]:
match = torch.where(match>0)

In [79]:
match

(tensor([0, 0, 0, 1, 1, 1, 2]),
 tensor([0, 1, 1, 0, 1, 1, 0]),
 tensor([0, 0, 1, 1, 0, 1, 1]),
 tensor([2, 1, 1, 1, 0, 2, 2]))

In [80]:
sample[match[-1]]

tensor([7, 3, 3, 3, 6, 7, 7])

In [81]:
expand[match[0]]

tensor([[[7, 0],
         [3, 3]],

        [[7, 0],
         [3, 3]],

        [[7, 0],
         [3, 3]],

        [[1, 3],
         [6, 7]],

        [[1, 3],
         [6, 7]],

        [[1, 3],
         [6, 7]],

        [[9, 7],
         [8, 5]]])

In [82]:
expand[match[0],match[1],match[2]]

tensor([7, 3, 3, 3, 6, 7, 7])